.TH DASH 1
.SH NAME
dash — command interpreter shell
.SH SYNOPSIS
.SH DESCRIPTION
.B dash is the standard command interpreter for the system.   The  current version  of 
.B dash is in the process of being changed to conform with the POSIX 1003.2 and 1003.2a specifications for the  shell.   This  version has  many features which make it appear similar in some respects to the Korn shell, but it is not a Korn shell clone (see ksh(1)).   Only  fea‐ tures  designated  by  POSIX, plus a few Berkeley extensions, are being incorporated into this shell.  This man page is not intended  to  be  a tutorial or a complete specification of the shell.
.SH OPTIONS
